import { cn } from "@/lib/utils"
import { BETA_VERSION } from "@/lib/version"

/**
 * Beta indicator. The number is generated by scripts/generate-version.mjs
 * (merge commits reachable from HEAD) on every `dev`/`build`, so it
 * advances on its own as the project is merged.
 */
export function BetaBadge({ className }: { className?: string }) {
  return (
    <span
      className={cn(
        "select-none text-[10px] font-medium uppercase tracking-wide text-muted-foreground/50",
        className,
      )}
      title="Vigía está en fase beta"
    >
      Beta v0.{BETA_VERSION}
    </span>
  )
}
