// GENERATED FILE — do not edit by hand.
// Regenerated by scripts/generate-version.mjs on every `pnpm dev`/`pnpm build`
// run. Counts merge commits reachable from HEAD, so it tracks how many
// times we've merged into main.
export const BETA_VERSION = 85
