#!/usr/bin/env node
// Regenerates lib/version.ts with the current merge-commit count reachable
// from HEAD, so the "Beta v0.N" badge always reflects how many times we've
// merged into main. Runs automatically before `pnpm dev` / `pnpm build`
// (see package.json "predev"/"prebuild" hooks), so it's fresh on every
// local run and on every Vercel deployment triggered by a merge to main.
import { execSync } from "node:child_process"
import { writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const rootDir = join(dirname(fileURLToPath(import.meta.url)), "..")
const outputPath = join(rootDir, "lib", "version.ts")

function countMerges() {
  try {
    const output = execSync("git rev-list --merges --count HEAD", {
      encoding: "utf-8",
      cwd: rootDir,
    }).trim()
    const count = Number.parseInt(output, 10)
    return Number.isFinite(count) && count > 0 ? count : null
  } catch {
    return null
  }
}

const merges = countMerges()

if (merges === null) {
  console.warn("[generate-version] Could not read merge count from git history; keeping existing lib/version.ts")
} else {
  const contents = `// GENERATED FILE — do not edit by hand.
// Regenerated by scripts/generate-version.mjs on every \`pnpm dev\`/\`pnpm build\`
// run. Counts merge commits reachable from HEAD, so it tracks how many
// times we've merged into main.
export const BETA_VERSION = ${merges}
`
  writeFileSync(outputPath, contents, "utf-8")
  console.log(`[generate-version] BETA_VERSION set to ${merges}`)
}
